version: '2'

services:
    users:
        image: product-service:latest
        ports:
            - "5005:5005"
        restart: always 
        environment:
        - "PORT=5005"
        - "DB_USERNAME=conectapis"
        - "DB_PASSWORD=Nicolas8032367."
        - "DB_HOST=192.168.0.13"
        - "DB_PORT=3306"
        - "DB=laikadblinux"
        - "SECRET_KEY=Juancho"
    products:
        image: user-service:latest
        ports:
            - "5004:5004"
        restart: always 
        environment:
        - "PORT=5004"
        - "DB_USERNAME=conectapis"
        - "DB_PASSWORD=Nicolas8032367."
        - "DB_HOST=192.168.0.13"
        - "DB_PORT=3306"
        - "DB=laikadblinux"
        - "SECRET_KEY=Juancho"
    authentication:
        image: authentication-service:latest
        ports:
            - "5001:5001"
        restart: always 
        environment:
        - "PORT=5001"
        - "DB_USERNAME=conectapis"
        - "DB_PASSWORD=Nicolas8032367."
        - "DB_HOST=192.168.0.13"
        - "DB_PORT=3306"
        - "DB=laikadblinux"
        - "SECRET_KEY=Juancho"
